version: "3.9"

services:
    book-library-api-dev:
        container_name: book-library-api-dev
        build:
            context: .
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 4000:4000
        command: "npm run dev"
        environment:
            PORT: 4000
            DB_CONNECTION_STRING: mongodb://mongo_db:27017/library
            SECRET_KEY: secret
            EXPIRATION_TIME: 25m
        depends_on:
            - mongo_db

    mongo_db:
        container_name: mongo_db
        image: mongo:6.0
        restart: always
        volumes:
            - mongo_db:/data/db
        ports:
            - 2717:27017

volumes:
    mongo_db:
