version: '3.9'

services:
  book-library-api-prod:
    build: .
    ports:
      - 4000:4000
    volumes:
        - .:/app
    container_name: book-library-api-prod
    environment:
      PORT: 4000
      DB_CONNECTION_STRING: mongodb://mongo_db:27017/library
      SECRET_KEY: secret
      EXPIRATION_TIME: 25m
    depends_on:
      - mongo_db
    command: "npm run start"
  
  mongo_db:
      container_name: mongo_db
      image: mongo:6.0
      restart: always
      ports:
        - 2717:27017
      volumes:
        - mongo_db:/data/db
    
volumes:
  mongo_db: